### PR TITLE
Wrote Jupyter notebook for the plot and data wrangling.

### PR DESCRIPTION
**Pull request by stevenleung2018**
Hi team,

I am getting a bit stuck on moving my code over to dash so I might just take a break from here.

Please see the code I have in this PR.  The Jupiter notebook code is working with some static input on the traits selected by the users (should come from checkboxes) and also the weights (should come from sliders).  

I have written a helper function which would return an Altair plot object as well as a DataFrame of the top 5 breeds (so 5 rows only) with the breed names, the traits selected, the score, the URLs to the images, etc. to be used by the subsequent dash code.

Please take a look at the code and see if you want me to do more.  I prefer my coding be limited to the current scope, i.e. please pick up the work before (e.g. the slidebars, etc.) and after (e.g. retrieving images).

I am also committing the data files for our convenience.

The notebook is only temporary.  It can be removed from the repo once we have created the `app.py` and other files.

Thanks.

Steven

### CODE REVIEW

**Comment by stevenleung2018** [comment]
I want to explain a bit on why I had to create the `BreedID` column in both data frames.  The reason is that when I tried to join the data frames on the `Breed` column, `pandas` appears to NOT work correctly on the `Breed` names with spaces in it.  I even tried by forcing the type of that column to `string`, and it still does not work correctly.  Since both `CSV` files were beautifully sorted, I just create `BreedID` columns in both data frames, enabling them to be joined correctly.

**Comment by stevenleung2018** [comment]
Just an idea, I think the slide-bars should allow the user to give negative values on the features.  For instance, if the user is very bothered by the shredding of the dog, the user can give a negative number to indicate such preference and the rank can be done accordingly.  FYI, my code is the score will take care of that automatically.

**Review by shivajena — APPROVED** [review]
Thanks Steven. I have implemented in pydash with some changes to weights which can be experimented further as we develop the app.

**Comment by shivajena** [comment]
> Just an idea, I think the slide-bars should allow the user to give negative values on the features. For instance, if the user is very bothered by the shredding of the dog, the user can give a negative number to indicate such preference and the ranking can be done accordingly. FYI, my code is the score will take care of that automatically.

Nice Idea Steven. For that, a bit of improvement needed on our dash code for flexible inputs for weights, wherein the user can assign weights to the features. If someone could code this input for the altair plot code, I can integrate into our dash code.

**Review by squisty — APPROVED** [review]

**Pull request merged**
